### PR TITLE
Add job posting date types

### PR DESCRIPTION
**Pull request by elliottsj**
Added frontmatter vars:
- `post_date`: date when job was posted
- `apply_date`: deadline for applicants to apply
- `start_date`: date when the work term starts

Any more necessary? End date maybe?

Also in jobs.html, should `apply_date` and `start_date` be displayed here?

### CODE REVIEW

**Comment by jwebbed** [comment]
An end date would be good if there is someway to make it stop showing it after that date? Maybe not publicly displayed, but at least for internal use.

**Comment by elliottsj** [comment]
Could hide it with JS. Or could hack together something that recompiles the site daily and excludes expired job postings.

**Comment by elliottsj** [comment]
For the 2nd option, that'd probably be a custom Jekyll plugin

**Comment by jwebbed** [comment]
I could look into that after I finish this quest in Diablo :+1:

**Comment by jwebbed** [comment]
How about we do both. Short term fix is Javascript, long term fix is writing a plugin. Javascript will be useful as well for the in between time before it recompiles. I'll work on it.

**Comment by elliottsj** [comment]
I think doing just the Jekyll plugin would be best; no need to spend time doing a js fix. If we recompile at midnight or 12:01, it'll be a couple minutes of delay at most

**Comment by jwebbed** [comment]
That's true.

**Comment by jwebbed** [comment]
I don't think we'll need to write an entire plugin in for this. We could use checks in the site to make sure everything is up to date. In terms of recompiling, could we just run a program on the server that just recompiles it at midnight?

**Comment by elliottsj** [comment]
Ah true, that might work.

**Comment by arkon** [comment]
Recompiling every night sounds good. It would also deal with not showing old events on the front page (might need some tweaks).

**Pull request merged**
