### PR TITLE
New style guideline page, new asset pipeline

### PR DESCRIPTION
**Pull request by elliottsj**
New style page:
screenshot 2015-01-16 01 46 02

And a more comprehensive asset pipeline using https://github.com/ixti/jekyll-assets/

From now on, assets should be placed in the `_assets/` directory and linked using the helpers described in the jekyll-assets README.

### CODE REVIEW

**Comment by arkon** [comment]
I need to add a bit more content to the style guide and maybe deal with tags in mobile first.

**Comment by arkon** [comment]
'ight, just need to add info about colours to the style guide and this should be good to go.

**Comment by jwebbed** [comment]
Is this good to go? @arkon @elliottsj

**Comment by elliottsj** [comment]
@jwebbed [Looks good to me](https://draft.cssu.ca), other than a bit of unfinished stuff on [the style page](https://draft.cssu.ca/style/) (no big deal though).

**Comment by elliottsj** [comment]
Huh, I just noticed the U of T logo cut off at the bottom:
screenshot 2015-01-17 14 29 01

**Comment by arkon** [comment]
Just need to add stuff about colors. I'll do that later today.
On Jan 17, 2015 2:28 PM, Spencer Elliott notifications@github.com wrote:@jwebbed Looks good to me, other than a bit of unfinished stuff on the style page (no big deal though).

**Comment by arkon** [comment]
@elliottsj Weird, doesn't seem to be using the right background-size

**Pull request merged**
