### PR TITLE
Tagging for posts

### PR DESCRIPTION
**Pull request by elliottsj**
Allows us to categorize news/events/jobs posts.

Still need to refine the layout & find any bugs before merging.

@arkon @jwebbed @GohNicho Pls review

### CODE REVIEW

**Comment by jwebbed** [comment]
Programatically looks great, the layout does need to be updated though, as currently this dosen't actually do anything unless I didn't notice it

**Comment by elliottsj** [comment]
@jwebbed There's a tag cloud at the bottom of the page, e.g.: 
screenshot 2014-09-29 14 57 41

**Comment by elliottsj** [comment]
@arkon Can you style the tag cloud?

**Comment by arkon** [comment]
Possibly?

**Comment by elliottsj** [comment]
#20 is fixed, so this feature should be good to go. Just need @arkon to make it a bit prettier :stuck_out_tongue_winking_eye: 

The tag cloud is generated like this:

``` html
<div class="tag-cloud">
  <a href="/tag/cssu" class="set-5">cssu</a>
  <a href="/tag/dev" class="set-1">dev</a>
  <a href="/tag/sponsor" class="set-1">sponsor</a>
</div>
```

The classes range from `"set-1"` to `"set-5"` and represent the relative number of posts with that tag. i.e. the `"set-5"` has the most posts.

**Comment by arkon** [comment]
So you just want bigger font sizes or something...? I'm not big on tag clouds.

On Oct 12, 2014 1:45 PM, Spencer Elliott notifications@github.com wrote:
#20 is fixed, so this feature should be good to go. Just need @arkon to make it a bit prettier :stuck_out_tongue_winking_eye:

The tag cloud is generated like this:

``` html
<div class="tag-cloud">
  <a href="/tag/cssu" class="set-5">cssu</a>
  <a href="/tag/dev" class="set-1">dev</a>
  <a href="/tag/sponsor" class="set-1">sponsor</a>
</div>
```

The classes range from `"set-1"` to `"set-5"` and represent the relative number of posts with that tag. i.e. the `"set-5"` has the most posts.

---

**Comment by elliottsj** [comment]
@arkon ¯_(ツ)_/¯ I thought it was the best way to categorize posts. Doesn't really need to be a traditional 'tag cloud' with the font sizes; maybe it should just be a list in a sidebar somewhere?

**Comment by jwebbed** [comment]
Merge it, deal with the conflicts plox

**Comment by arkon** [comment]
Styling it now, don't merge yet!

EDIT: I lied, still installing Ruby 2.1.3.

**Comment by arkon** [comment]
Pour example:
image

**Comment by elliottsj** [comment]
Merging; we can fix issues on draft if necessary

**Comment by elliottsj** [comment]
Tags look good: http://cssu.herokuapp.com/tag/cssu/

**Pull request merged**
